flux_local/manifest.py
setup.cfg
tests/test_manifest.py

Allow reading/writing to a manifest file. Writing a manifest file can be useful to checkpoint all the expected primary artifacts of the cluster and used for driving tests, where just discovering artifacts form the cluster may result in unexpectedly missing some (e.g. if a kustomization is misconfigured)

Allow reading/writing to a manifest file

---

flux_local/manifest.py
setup.cfg

Update the manifest data model to include `HelmRelease` `values`. The manifest is compacted when persisted, and now the same object can be used for a raw release, or just persisted manifest.
Increase a breaking change to update all objects to be pyndantic models to simplify how exclusion works so that it can work on nested objects.

Streamline manifest output format

---

README.md

I think the link is currently pointing to the wrong project :-)

Fix link to documentation in readme

---

flux_local/git_repo.py

Avoid creating unnecessary branches when creating a worktree

Avoid creating unnecessary branches when creating a worktree

---

README.md
flux_local/git_repo.py
flux_local/manifest.py
flux_local/tool/build.py
flux_local/tool/diff.py
flux_local/tool/get.py
flux_local/tool/selector.py
tests/testdata/cluster/apps/prod/configmap.yaml

Update the `git_repo` building to have a shared selectors for querying cluster objects. These are now shared between `flux-local` commands `get`, `diff`, and `build` and shared across resource types.

Share flags and building between commands for consistency

---

flux_local/git_repo.py
tests/testdata/flux_local/get_ks.yaml
tests/testdata/flux_local/manifest.yaml

Update the default namespace selection to allow all namespaces. The previous behavior of a default namespace was intended for Kustomizations, which is preserved. Also the command line tool sets a default namespace already, preserving behavior.

Fix default namespace selection for HelmReleases to return all

---

flux_local/git_repo.py
flux_local/kustomize.py
tests/test_kustomize.py

Run fewer kustomize build commands when building the manifest by checkpointing the output of the commands to
a temporary file before chaining the grep commands.

Run fewer kustomize builds in manifest build

---

flux_local/git_repo.py
flux_local/kustomize.py
tests/test_kustomize.py

Now for a git repo with two clusters and 11 kustomizations each and 30 helm repos each it's about 4-5x faster:
```
$ time flux-local get cluster -o yaml
real	0m1.922s
user	0m7.288s
sys	0m0.864s
```
```
$ time flux-local get hr -A
real	0m1.868s
user	0m6.430s
sys	0m0.843s
```

Speed up manifest building by parallelizing

---

flux_local/git_repo.py
flux_local/tool/diff.py
tests/test_git_repo.py
tests/tool/testdata/get_ks_path.yaml
tests/tool/testdata/get_ks_path_ks.yaml

Speed up flux-local get and diff by:
- Running build and grep commands in parallel
- Reusing build output with a visitor object to preserve build contents
Introduces a `ResourceVisitor` which can get invoked with the content of the build. The `git_repo` build logic is refactored into an async method that can run tasks in parallel and itself be parallelized.

Performance improvements to flux-local get and diff

---

flux_local/command.py
flux_local/kustomize.py
tests/test_kustomize.py
tests/testdata/cluster2/apps/kustomization.yaml

Flux allows automatically creating a `kustomization.yaml` on the fly when there isn't one. This replicates that behavior by:
- including yaml files directly in the output
- Running `kustomize build` on subdirectories that do have a kustomziation file
Introduce a new task abstraction to allow piping data between tasks that are not just command line outputs. The fluxtomization does the equivalent work of a kustomize build but in a mix of python and cli, and the new abstraction allows us to put it at the start of the chain.
The testdata file in cluster2/apps that was removed was previously added as a stopgap and now it is no longer needed, matching the original layout of the cluster.
Issue #78

Fluxtomize resources without a kustomization present

---

flux_local/helm.py
flux_local/kustomize.py
flux_local/manifest.py
flux_local/tool/build.py
flux_local/tool/diff.py
flux_local/tool/flux_local.py
flux_local/tool/visitor.py
tests/tool/testdata/build_helm.yaml

Add flags to control skip secret before, enabled by default. Add flags for controlling the number of output lines in the unified diff.

Flux diff flags for configuring output (skip secrets, num context lines)

---

flux_local/git_repo.py
flux_local/tool/visitor.py
tests/test_git_repo.py

Update the visitor API to be async so that we can add more functionality into it, such as combing the helm inflation in the kustomization inflation APIs.
Issue #90

Change visitor API to async to support future features

---

flux_local/tool/diff.py

Diff output as markdown for easier integration in CI as a github action, which can't really iterate and loop over diffs easily.

Diff output as markdown for easier integration in CI

---

flux_local/tool/diff.py
flux_local/tool/visitor.py
tests/tool/test_diff.py

Update the formatting based on experience trying to use the old format in CI. This reverts the markdown change, just putting the file information in the diff.

Update structured output based on experience using in CI

---

flux_local/git_repo.py
flux_local/tool/build.py
flux_local/tool/diff.py
flux_local/tool/visitor.py
tests/test_git_repo.py
tests/tool/testdata/build_helm.yaml

For my cluster with ~20 Kustomizations, 40 HelmRepos, and 50 HelmReleases, this means a single diff takes 26 seconds to compute where it used to take around 2 minutes.
This includes a breaking change to the visitor API to pass both the cluster and kustomization path rather than changing depending on the context.
Issue #89

Improve diff helm performance by only templating on kustomization diffs

---

flux_local/tool/diff.py
flux_local/tool/flux_local.py

Improve multiline string output for all diffs when they are in the middle of an object. Previously this logic was only applied to the final output, not intermediate diffs.

Improve multiline string output for all diffs

---

README.md
flux_local/tool/get.py
tests/tool/testdata/get_ks.yaml
tests/tool/testdata/get_ks2.yaml
tests/tool/testdata/get_ks_path.yaml
tests/tool/testdata/get_ks_path_ks.yaml
tests/tool/testdata/get_ks_wide.yaml

Update the `flux get ks` command to have a flag `-o wide` that will generate Helm stats, hiding them by default.
```
$ time flux-local get ks -o wide
...
real	0m4.173s
user	0m9.874s
sys	0m1.155s
```
```
$ time flux-local get ks
...
real	0m0.570s
user	0m0.533s
sys	0m0.084s
````

Do not expand help releases on get ks by default

---

flux_local/git_repo.py
flux_local/kustomize.py
flux_local/manifest.py
tests/tool/testdata/get_cluster_yaml.yaml

Add ClusterPolicy objects to manifest for Issue #43 
Contains multiple performance improvements since we're adding another object type to fetch, so now filtering will happen with fewer commands.

Add ClusterPolicy objects to manifest

---

README.md
flux_local/git_repo.py
flux_local/kustomize.py
flux_local/manifest.py
flux_local/tool/test.py
tests/test_kustomize.py
tests/tool/testdata/test_hr_policy.yaml

Add kyverno policy checking e.g. 
```
flux-local test --enable-helm --enable-kyverno
```
Includes a breaking change for the `Kustomize.stash()` call.
Issue #43

Add support for testing kyverno policies

---

README.md
flux_local/command.py
flux_local/tool/diff.py
flux_local/tool/selector.py
tests/tool/test_flux_local.py
tests/tool/testdata/diff_hr_external.yaml
tests/tool/testdata/diff_ks_external.yaml

Add support for running an external diff command, and update README with examples with dyff.
Issue #101

Add support for external diff commands

---

flux_local/git_repo.py

Improve exception handling to give a slightly more useful error message when an invalid path is specified.
```
~/home-ops-2$ flux-local get hr -A --path .
Command '(None) kustomize cfg grep spec.sourceRef.kind=GitRepository' failed with return code 1
Error: MalformedYAMLError: yaml: mapping values are not allowed in this context
flux-local error:  Error building Fluxtomization in '/home/allen/home-ops-2' path '.': Command '(None) kustomize cfg grep spec.sourceRef.kind=GitRepository' failed with return code 1
Error: MalformedYAMLError: yaml: mapping values are not allowed in this context
Try specifying another path within the git repo?
```

Improve error messages for invalid kustomization paths

---

flux_local/helm.py
flux_local/tool/test.py

Add additional flags to `flux test` for passing directly through to helm template. Updates the test runner with ability to filter out some tests by node id.

Add support for running specific api versions with helm template

---

flux_local/tool/test.py

This was previously broken in https://github.com/allenporter/flux-local/pull/115

Fix flux test bug: Ensure test path argument is optional

---

flux_local/git_repo.py

Resolve the process and root paths when comparing so that any sym links will be resolved. This allows paths to be compared against each other so we can determine the relative path to process within the repo.
Fixes Issue #119

Resolve the process and root paths when comparing

---

.github/workflows/lint.yaml

Update ruff configuration to match rules in https://github.com/allenporter/repo-conformance

Remove stale reference to flake8

---

flux_local/tool/flux_local.py

so that they are still visible if you redirect stdout to a file (e.g. for capturing diff output)

Print errors to stderr instead of stout

---

flux_local/helm.py
flux_local/manifest.py
tests/test_manifest.py
tests/testdata/cluster/infrastructure/configs/helm-repositories.yaml
tests/tool/testdata/build.yaml
tests/tool/testdata/build_helm.yaml
tests/tool/testdata/get_cluster_yaml.yaml

Add support for HelmRepository type oci.
See https://fluxcd.io/blog/2022/11/verify-the-integrity-of-the-helm-charts-stored-as-oci-artifacts-before-reconciling-them-with-flux/ for an example on how to set up.
This was added following the pattern in https://github.com/onedr0p/home-ops/commit/5ca73a5e518a8610fb408a70db5e2839bbdfe125

Add support for HelmRepository type oci

---

action/diff/action.yml
flux_local/tool/diff.py
flux_local/tool/visitor.py

Add a `strip-attrs` option to the diff action that allows removing labels and annotations that add to diff noise.
Issue #203

Add option to strip labels and annotations in diff action

---

action/diff/action.yml

Strip these additional labels found on kube-prometheus-stack charts, e.g. https://github.com/allenporter/k8s-gitops/pull/1143#issuecomment-1565340720
Issue #203

Skip 'chart' and 'app.kubernetes.io/version' labels

---

flux_local/tool/diff.py
flux_local/tool/visitor.py

Update the --strip-attrs flag to parse a list from a csv. Update the strip attrs function to also strip labels from templates embedded in the deployment spec.
Issue #203

Accept a list of comma separated values for --strip-attrs and strip spec template labels

---

action/diff/action.yml
flux_local/tool/diff.py
tests/tool/testdata/diff_hr_external_limit.yaml
tests/tool/testdata/diff_hr_limit.yaml
tests/tool/testdata/diff_ks_yaml_limit.yaml

Add a default limit so that very large diffs do not fail github actions
Issue #207

Add --limit-bytes to diff command to truncate output in github actions

---

.github/workflows/flux-local-diff.yaml
README.md

Add pr id to comments to ensure diffs end up on the right PR.

Update default actions to include PR id in comment id

---

flux_local/git_repo.py
flux_local/manifest.py
tests/test_git_repo.py
tests/testdata/cluster4/README.md
tests/testdata/cluster4/apps/monitoring/kubernetes-dashboard/helmrelease.yaml
tests/testdata/cluster4/apps/monitoring/kubernetes-dashboard/ks.yaml
tests/testdata/cluster4/apps/monitoring/kubernetes-dashboard/kustomization.yaml
tests/testdata/cluster4/apps/monitoring/kustomization.yaml
tests/testdata/cluster4/apps/monitoring/namespace.yaml
tests/testdata/cluster4/flux/apps.yaml
tests/testdata/cluster4/flux/config/cluster.yaml
tests/testdata/cluster4/flux/config/flux.yaml
tests/testdata/cluster4/flux/config/kustomization.yaml
tests/testdata/cluster4/flux/repositories/kubernetes-dashboard.yaml
tests/testdata/cluster4/flux/repositories/kustomization.yaml
tests/tool/testdata/diff_ks_yaml_empty_sources.yaml
tests/tool/testdata/get_cluster2.yaml
tests/tool/testdata/get_cluster3.yaml
tests/tool/testdata/get_cluster4.yaml
tests/tool/testdata/get_ks2.yaml

Issue #225
Issue #198
Reproduces the issue with:
```
$ flux-local get cluster --path tests/testdata/cluster4/
NAME                                 PATH                                                              KUSTOMIZATIONS    
cluster-apps-kubernetes-dashboard    ./tests/testdata/cluster4/apps/monitoring/kubernetes-dashboard    1                 
cluster                              ./tests/testdata/cluster4/flux                                    2                 
```

Add a test repo to reproduce a connectivity issue

---

flux_local/tool/build.py
flux_local/tool/diff.py
flux_local/tool/flux_local.py
flux_local/tool/get.py
flux_local/tool/selector.py
flux_local/tool/test.py

Update build to use the same pattern as other tools, and share some of the command flags with other selector based commands.

Refactor build cli command line flags

---

.github/workflows/flux-local-diff.yaml
.github/workflows/flux-local-test.yaml
action/diff/action.yml
flux_local/tool/test.py
tests/tool/testdata/test_hr6.yaml

Fix a bug in flux-test where kwargs were not passed properly.
Update test strategy to explicitly test each test cluster.
Issue #251

Fix regression in api-versions and flux-local test

---

flux_local/kustomize.py
tests/test_kustomize.py

Follow the same flags as set by flux https://fluxcd.io/flux/faq/#what-is-the-behavior-of-kustomize-used-by-flux to have similar `kustomize build` behavior.

Change default kustomize build behavior to match flux

---

.github/workflows/flux-local-diff.yaml
flux_local/git_repo.py
flux_local/tool/diff.py
flux_local/tool/get.py
flux_local/tool/selector.py
flux_local/tool/visitor.py
tests/tool/testdata/get_cluster3.yaml
tests/tool/testdata/get_ks5_all.yaml
tests/tool/testdata/get_ks_path_ks.yaml

- Add an explicit simplification for flux-system as the root of the cluster
- Don't add circular dependencies when doing automatic root identification
- Fix kustomization namespace output
- Address issues with not using relative paths

Improve kustomization handling for more complex repo setups

---

flux_local/git_repo.py
flux_local/manifest.py
flux_local/tool/get.py
flux_local/tool/test.py
tests/__snapshots__/test_git_repo.ambr
tests/test_manifest.py
tests/tool/__snapshots__/test_diff_ks.ambr
tests/tool/__snapshots__/test_get_cluster.ambr

Remove support for multiple clusters in a single path
This is a breaking change that removes the `name` and `namespace` fields from the `Cluster` object so they no longer act like fake kustomizations.
Issue #390

Remove support for multiple clusters in a single path

---

flux_local/git_repo.py
tests/__snapshots__/test_git_repo.ambr
tests/test_git_repo.py

Skip unnecessary kustomize cfg step when scanning the cluster

---

flux_local/command.py
flux_local/exceptions.py
flux_local/git_repo.py
flux_local/kustomize.py
flux_local/tool/test.py

Improve error messages by catching the common messages, supressing unnecessary verbose logging when necessasary.

Improve error messages for shell commands

---

flux_local/git_repo.py
tests/test_git_repo.py
tests/testdata/cluster7/clusters/home/charts.yaml

Add support for a Kustomization that refers to an absolute path. This will be treated as if it were relative to the root.
Fixes #407

Fix support for Kustomizations with absolute paths

---

flux_local/git_repo.py
tests/__snapshots__/test_git_repo.ambr

Improve traversal performance. Speed up by running kustomizations in parallel again, which is now possible after previous simplifications. Even for a small cluster we see a large impact win:
Old:
```
NAME            REVISION    CHART                       SOURCE          
weave-gitops    4.0.22      flux-system-weave-gitops    weave-charts    
real    0m4.229s
user    0m5.476s
sys     0m2.140s
```
New:
```
NAME            REVISION    CHART                       SOURCE          
weave-gitops    4.0.22      flux-system-weave-gitops    weave-charts    
real    0m0.996s
user    0m2.304s
sys     0m0.376s
```

Improve kustomization traversal performance

---

flux_local/git_repo.py
flux_local/image.py
flux_local/manifest.py
flux_local/tool/get.py
flux_local/tool/visitor.py
tests/tool/__snapshots__/test_get_cluster.ambr
tests/tool/test_get_cluster.py

Follow on from #443 by also adding HelmRelease images to the manifest. This also contains cleanup of other unused code from the initial PR adding container images.
Issue #434
Example usage
```
$ flux-local get cluster --path tests/testdata/cluster/ -o yaml --enable-images
---
clusters:
- path: tests/testdata/cluster
kustomizations:
- name: apps
namespace: flux-system
path: tests/testdata/cluster/apps/prod
helm_repos: []
helm_releases:
- name: podinfo
namespace: podinfo
chart:
name: podinfo
repo_name: podinfo
repo_namespace: flux-system
images:
- public.ecr.aws/docker/library/redis:7.0.6
- ghcr.io/stefanprodan/podinfo:6.3.2
cluster_policies: []
- name: flux-system
namespace: flux-system
path: tests/testdata/cluster/clusters/prod
helm_repos: []
helm_releases: []
cluster_policies: []
- name: …
```

Add HelmRelease images to cluster manifest

---

flux_local/git_repo.py
flux_local/tool/diff.py
flux_local/tool/visitor.py
tests/__snapshots__/test_git_repo.ambr
tests/test_git_repo.py
tests/tool/__snapshots__/test_diff_ks.ambr

Remove the unnecessary code from multi-cluster diff. Multi-cluster repos are still supported, just not with a single diff command.

Remove complexity from multi-cluster diff

---

flux_local/command.py

Improve timeout error message when a subcommand fails to complete in time to show the actual command that was run.
Example:
```
FAILED tests/tool/test_test.py::test_test_hr[policy] - flux_local.exceptions.CommandException: Command 'flux-local test --enable-helm --enable-kyverno tests/testdata/cluster' timed out
```

Improve timeout error message

---

action/diff/action.yml
action/test/action.yml

Fixes https://github.com/onedr0p/home-ops/actions/runs/7290504875/job/19867462979#step:14:42 where the pip cache was looking at the wrong requirements file.
```
Error: No file in /home/runner/work/home-ops/home-ops matched to [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```
Issue #437

Set cache dependency paths based on action

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/container-release.yaml
.github/workflows/container-test.yaml
Dockerfile

Adds container workflow for builds for test and release. I moved the devcontainer Dockerfile to the devcontainer folder.
~~I didn't know the best way to add the kyverno CLI to the container since I wanted to do it in a multiarch way.~~

feat: add container build and workflows

---

Dockerfile

This was a mistake on my end I forgot to revert on the original PR

fix: change CMD to ENTRYPOINT in Dockerfile

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Update the devcontainer to remove unnecessary code, and update to use a workspace with a volume mount for improved performance.

Streamline devcontainer

---

flux_local/tool/format.py
flux_local/tool/get.py

Add --output-file flag to get cluster action to allow writing output directly to a file. This makes it easier to invoke from a docker container and will simplify many of the github actions.
Example usage:
```
$ flux-local get cluster --path tests/testdata/cluster -o yaml --output-file=/tmp/yaml
```
Tested manually, and implicitly through default argument using `/dev/stdout`.
Fixes #455

Add --output-file flag to get cluster action

---

action/diff/action.yml
flux_local/tool/build.py
flux_local/tool/diff.py

Add the --output-file command for `diff` and `build`. Also update the diff action to use the output file command as in the example in the feature request.
Fixes #455

Add --output-file for build and diff and use in action

---

Dockerfile

Currently the container runs as root. This change is needed because of the following error when using the container in Github actions since Git will see the files as owned by 1001 instead of what the container expects of `root`
```
Traceback (most recent call last):
File "/usr/local/bin/flux-local", line 33, in <module>
sys.exit(load_entry_point('flux-local', 'console_scripts', 'flux-local')())
File "/app/flux_local/tool/flux_local.py", line 61, in main
asyncio.run(action.run(**vars(args)))
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/app/flux_local/tool/diff.py", line 278, in run
await git_repo.build_manifest( …
```

fix: change running user to 1001

---

action/diff/action.yml
tests/testdata/cluster/apps/base/podinfo/kustomization.yaml

Fix broken diff action output

---

flux_local/tool/diff.py

Fix issue where diffs for no helm releases breaks the action output.

Honour --output-file when there are not Helm Releases

---

flux_local/manifest.py
flux_local/tool/get.py
flux_local/values.py
mypy.ini
requirements.txt
setup.cfg
tests/test_kustomize.py
tests/test_manifest.py
tests/test_values.py

Allows removing a lot of code, given mashumaro is simpler. pydantic also had a very odd upgrade strategy, and is growing too complex for use in this project.

Use mashumaro for yaml parsing and drop pydantic

---

flux_local/values.py

Fix log messages such as this:
`Unable to find SubstituteReference for flux-system/alertmanager-silencer: cluster-settings`

Fix log messages for invalid value references

---

flux_local/values.py
tests/test_values.py

Ensure that when a secret is missing, the fallback to the values placeholder still happens. This was an unintentional behavior change when adding post build substitutions.

Fix regression with fallback secret placeholders

---

flux_local/git_repo.py
flux_local/tool/diff.py

Following the discussion on discord, I've extended the behaviour of `create_worktree` to use a branch and not be detached. This allows us to compare two branch, the current and `main` for example easily.

feat: allow diff to take a branch name as origin using worktree

---

flux_local/kustomize.py
tests/test_kustomize.py

Improve command output for cases like parsing helm values that contain invalid values.
#731

Improve error messages for parse failures

---

.pre-commit-config.yaml
flux_local/command.py
flux_local/git_repo.py
flux_local/kustomize.py
flux_local/values.py
tests/__snapshots__/test_git_repo.ambr
tests/testdata/cluster/apps/prod/certificates.yaml
tests/testdata/cluster/apps/prod/kustomization.yaml
tests/testdata/cluster/clusters/prod/flux-system/cluster-config.yaml
tests/tool/__snapshots__/test_build.ambr
tests/tool/__snapshots__/test_diff_ks.ambr

Fix build in postbuild substitution

---

flux_local/helm.py
flux_local/tool/selector.py

Add a flag `--registry-config` that can be used as a pass through to the helm command.
#717
#301

Add a pass through --registry-config flag

---

flux_local/helm.py
flux_local/manifest.py
flux_local/tool/build.py
flux_local/tool/test.py
flux_local/tool/visitor.py
tests/test_helm.py
tests/test_manifest.py
tests/testdata/cluster9/README.md
tests/testdata/cluster9/apps/podinfo/kustomization.yaml
tests/testdata/cluster9/apps/podinfo/podinfo.yaml
tests/testdata/cluster9/apps/podinfo/repository.yaml
tests/tool/__snapshots__/test_build.ambr
tests/tool/__snapshots__/test_get_hr.ambr

Add support for parsing an OCIRepository https://fluxcd.io/flux/components/helm/helmreleases/#chart-reference
Obsoletes https://github.com/allenporter/flux-local/pull/709

Add support for chartRef in a HelmRelease

---

flux_local/tool/diff.py
tests/testdata/cluster7/flux/apps/cloudflare/release.yaml
tests/testdata/cluster7/flux/charts/app-template.yaml
tests/tool/__snapshots__/test_get_hr.ambr

Adding additional repository examples, but they don't reproduce the issue.

Fix issue with collecting OCIRepositories during diff

---

README.md
flux_local/tool/build.py
tests/testdata/cluster9/apps/podinfo/repository.yaml
tests/tool/__snapshots__/test_build.ambr
tests/tool/test_build.py

This is a breaking change that updates the format of the `flux build` command to have parity with `get` and `diff` commands.
Example to build a single kustomziation:
```bash
$ flux-local build ks apps --path tests/testdata/cluster/
```
Example to inflate a single helm release:
```bash
$ flux-local build hr podinfo -n podinfo --path tests/testdata/cluster
```
The old behavior `flux-local build tests/testdata/cluster/` can still be achieved with `build all`:
```bash
$ flux-local build all tests/testdata/cluster/
```
Fixes #795

Update flux build to have parity with other flux commands

---

flux_local/manifest.py
flux_local/values.py
tests/__snapshots__/test_values.ambr
tests/test_values.py
tests/testdata/cluster/apps/prod/certificates.yaml
tests/testdata/cluster/clusters/prod/apps.yaml
tests/testdata/cluster/clusters/prod/flux-system/cluster-secrets.yaml
tests/tool/__snapshots__/test_build.ambr
tests/tool/__snapshots__/test_diff_ks.ambr

Fix an issue where substitution values (that are from secrets or can't be found) were not unique which may result in resource names that are set with the same value. This may mask bugs if users do not set resource values to the same thing when using secrets.
Fixes #754

Set unique placeholder values for each substitution

---

.cruft.json
.gitignore
script/run-mypy.sh

Automatically generated PR from `repo_conformance` to apply updates using `scruft`.

Apply cruft updates

---

flux_local/values.py
tests/testdata/cluster8/apps/podinfo-values.yaml
tests/testdata/cluster8/apps/podinfo.yaml
tests/tool/__snapshots__/test_build.ambr

Allow empty YAML values files.
Perform a deep merge instead of shallow, for better helm values patching.
(I was unable to locally run the tests, would like to check via the pipeline)

Add deep-merge of values, and allow empty values file

---

flux_local/values.py
tests/test_values.py
tests/testdata/cluster8/apps/podinfo-values.yaml
tests/testdata/cluster8/apps/podinfo.yaml
tests/tool/__snapshots__/test_build.ambr

https://fluxcd.io/flux/components/helm/helmreleases/#values-references specifies that `values` are merged last after any `valuesFrom` references.
Fixes #813

Fix merging of values to override inline values last

---

flux_local/kustomize.py
flux_local/manifest.py
flux_local/resource_diff.py
flux_local/tool/diff.py
flux_local/visitor.py
tests/test_manifest.py
tests/test_resource_diff.py

Improve HelmRelease dependency tracking for diffs by tracking changes in dependencies like ConfigMaps and HelmReleases.
Fixes #817

Improve HelmRelease dependency tracking for diffs

---

Dockerfile

fix: remove `kubectl` from Dockefile

---

action/test/action.yml

I noticed when implementing `action/test` the caching step took a significant amount of time compared to the actual business logic. `action/diff` doesn't seem to have this behavior.
`action/diff` is using `actions/setup-python@v5`, while `action/test` is using `actions/setup-python@v4`. 
This is important as that action has updated `actions/cache@v4` which uses the newer V2 cache. Additionally, all prior versions of `actions/cache` will start failing in workflows on 2025-02-01.
Solution is to update `actions/setup-python` to the latest version.
- https://github.com/actions/setup-python/pull/1007
- https://github.com/actions/toolkit/discussions/1890

feat(actions): bump actions/setup-python to v5

---

flux_local/tool/selector.py
tests/tool/__snapshots__/test_diff_ks.ambr
tests/tool/__snapshots__/test_get_hr.ambr
tests/tool/test_get_hr.py

Add --label-selector command line flags

---

flux_local/git_repo.py
flux_local/helm.py
flux_local/tool/build.py
flux_local/tool/selector.py

Example before and after usage:
```
$ flux-local build ks --path tests/testdata/cluster | kustomize cfg count
Certificate: 4
ClusterPolicy: 1
ConfigMap: 2
GitRepository: 1
HelmRelease: 3
HelmRepository: 3
Kustomization: 4
Namespace: 1
$ flux-local build ks --path tests/testdata/cluster --skip-kinds=ClusterPolicy,Certificate | kustomize cfg count
ConfigMap: 2
GitRepository: 1
HelmRelease: 3
HelmRepository: 3
Kustomization: 4
Namespace: 1
```
Fixes #824

Add a flag --skip-kinds to omit kind from the output

---

flux_local/image.py
tests/test_image.py
tests/testdata/cluster/infrastructure/configs/ceph-cluster.yaml
tests/testdata/cluster/infrastructure/configs/database.yaml
tests/testdata/cluster/infrastructure/configs/kustomization.yaml
tests/tool/__snapshots__/test_build.ambr
tests/tool/__snapshots__/test_get_cluster.ambr

Hey Allen,
Not sure if this is the best way forward for this request, but I am trying to collect more images to pre-pull them when I see updates.
Let me know if you want to improve this.

Detect more images from commonly used crds

---

requirements.txt
setup.cfg

Perhaps it's used in github actions eg by cruft, but the actual package doesn't need this so let's run lean.
I looked at some git history and this was an early addition which I think is not used by anything. I didn't check if anything else needs it. I guess pytest shouldn't really be there either but that's a different story. I have not really ran the github actions in my fork but the tests in this repo should surface any issues I guess!
The motivation behind removing slugify is because it is installing unidecode which is GPL, so it restricts commercial usage. Feel free to close if I am wrong about this!

Remove unnecessary slugify dependency

---

flux_local/tool/flux_local.py

Fix "RuntimeError: Event loop is closed" by running the event loop until it closes.

Fix "RuntimeError: Event loop is closed"

---

flux_local/store/__init__.py
flux_local/store/artifact.py
flux_local/store/in_memory.py
flux_local/store/status.py
flux_local/store/store.py
tests/store/test_in_memory.py

The store module provides a central, type-safe repository for tracking the state, definitions,
and artifacts of Kubernetes custom resources (CRs) during a flux-local run.
- Uses NamedResource as the key for all objects.
- Stores values as dataclass instances from manifest.py for type safety.
- Provides query and update APIs for controllers (e.g., SourceController, KustomizeController).
This abstract interface allows for various implementations (in-memory, persistent, etc.).

Add a foundational storage module

---

requirements.txt

This addresses https://github.com/allenporter/flux-local/issues/942 which is an issue in oras==0.2.34
https://github.com/oras-project/oras-py/pull/208
~Considered pinning the version, but it seems oras releases quite frequently, so hopefully the fix will be in the next release.~
The more I look at this, the more I think `oras` should be pinned and have renovate update it. This would have been prevented by the failed run, similar to https://github.com/allenporter/flux-local/pull/941

pin oras in requirements.txt (avoid bug in oras 0.2.34)

---

flux_local/helm_controller/controller.py
flux_local/manifest.py
tests/kustomize_controller/__snapshots__/test_controller.ambr
tests/kustomize_controller/test_controller.py

Fixes for new helm controller where they would get stuck because:
- Helm update happens before HelmReposistory objects are complete
- HelmRepository objects from `kustomize build` not applied to storage properly

Fixes for new Helm Controller reconciliation
