allenporter/flux-local

.github/workflows/pages.yaml
Configure pdoc and github pages copied from configuration in ical.
=> Configure pdoc and github pages

flux_local/command.py, flux_local/flux_local.py, flux_local/helm.py, flux_local/kustomize.py, flux_local/manifest.py, flux_local/repo.py, flux_local/tool/__init__.py, flux_local/tool/flux_local.py, requirements.txt, setup.cfg, tests/test_helm.py
Add a flux-local command line tool
Issue #35
=> Add a flux-local command line tool

flux_local/helm.py, flux_local/tool/flux_local.py
=> Add command line option to skip crds in build and diff

flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/manifest.py
=> Refactor commands into separate classes/files

.github/workflows/flux-local-test.yaml, .github/workflows/python-package.yaml, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/manifest.py, flux_local/tool/test.py, flux_local/tool/test_kustomization.py, requirements.txt, setup.cfg, tests/test_flux_local.py
=> Add flux-local test command

.github/workflows/lint.yaml, .pre-commit-config.yaml, flux_local/kustomize.py, requirements.txt, setup.cfg
Upgrade linters to use ruff which is significantly faster than pylint.
=> Upgrade linters to use ruff

README.md, flux_local/__init__.py, flux_local/tool/__init__.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/format.py, flux_local/tool/get.py, tests/test_flux_local.py
Add a command `flux-local get` to support Kustomizations and HelmReleases
Issue #35 
Rename submodule for exported APIs which happened in #40
=> Add flux-local get command to CLI

README.md, flux_local/git_repo.py, flux_local/manifest.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, tests/test_flux_local.py, tests/testdata/cluster/apps/prod/configmap.yaml, tests/testdata/cluster/apps/prod/kustomization.yaml
Improve flux-local diff for kustomizations
Issue #35
=> Improve flux-local diff for kustomizations

README.md, flux_local/git_repo.py, flux_local/helm.py, flux_local/tool/diff.py, tests/test_flux_local.py, tests/testdata/cluster/apps/prod/podinfo-values.yaml
Add flux-local hr diff command, and update the documentation.
This includes a breaking change to the path argument, making it an optional flag rather than an optional positional.
Issue #35
=> Add flux-local hr diff command

.pre-commit-config.yaml, .yaml-lint.yaml, CONTRIBUTING.md, flux_local/tool/diff.py, requirements.txt, tests/test_flux_local.py, tests/testdata/cluster/infrastructure/controllers/metallb-release.yaml, tests/testdata/flux_local/build.yaml, tests/testdata/flux_local/build_helm.yaml, tests/testdata/flux_local/diff_hr.yaml, tests/testdata/flux_local/diff_hr_all.yaml, tests/testdata/flux_local/diff_hr_all_namespaces.yaml, tests/testdata/flux_local/diff_hr_not_found.yaml, tests/testdata/flux_local/diff_hr_not_found_all_namespaces.yaml, tests/testdata/flux_local/diff_hr_not_found_namespace.yaml, tests/testdata/flux_local/diff_ks.yaml, tests/testdata/flux_local/get_hr.yaml, tests/testdata/flux_local/get_hr_name.yaml, tests/testdata/flux_local/get_hr_namespace.yaml, tests/testdata/flux_local/get_ks.yaml, tests/testdata/flux_local/manifest.yaml
Replace command line tests with golden file tests
=> Replace command line tests with golden file tests

README.md, flux_local/tool/selector.py
Update README and fix path bug based on examples.
=> Update README and fix path bug

README.md, flux_local/tool/format.py, tests/tool/testdata/get_cluster_yaml.yaml
Strip newline at the end of the yaml document
Issue #45
=> Strip newline at the end of the yaml document

flux_local/kustomize.py
=> Update fluxtomize comments

flux_local/git_repo.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/selector.py, flux_local/tool/visitor.py, tests/tool/testdata/build.yaml, tests/tool/testdata/diff_hr_yaml.yaml, tests/tool/testdata/diff_ks_yaml.yaml
Add yaml diff output support so diffs can be inspected programmatically
=> Diff improvements: support yaml output and skipping secrets

flux_local/tool/diff.py
Add a flag for diff path comparisons to support diffs from a CI.
=> Add a flag for diff path comparisons

flux_local/git_repo.py, flux_local/tool/visitor.py, tests/test_git_repo.py
Move the content building to be performed from the visitor in preparation for changing the diffing logic to do transformation while producing the objects.
Issue #90
=> Refactor the build output so that it happens in the visitor

CONTRIBUTING.md, flux_local/helm.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/visitor.py, tests/tool/test_diff.py, tests/tool/testdata/build_helm.yaml
Improve diff output to include the individual object names, rather than just an entire text diff.
Issue #90 
Issue #89
=> Improve structured output for diff ks and hr

flux_local/__init__.py, flux_local/command.py, flux_local/exceptions.py, flux_local/git_repo.py, flux_local/helm.py, flux_local/kustomize.py, flux_local/manifest.py, flux_local/tool/flux_local.py, flux_local/tool/visitor.py
Improve exception handling in flux-local library and tool. Add a new FluxException base class used by all exception types.
=> Improve exception handling

flux_local/tool/diff.py
Fix flux-local ks diff yaml output which was previously omitted.
=> Fix flux-local ks diff yaml output

.pre-commit-config.yaml
Update ruff configuration based on checks from https://github.com/allenporter/repo-conformance
=> Update ruff configuration

.github/workflows/flux-local-diff.yaml, .github/workflows/flux-local-test.yaml, README.md, action/diff/action.yml, action/test/action.yml
Copy actions from flux-local-action to this repo, and update the test action to do tests on the repo.
=> Move actions from flux-local-action to this repo

flux_local/command.py, flux_local/git_repo.py, flux_local/tool/flux_local.py
Improve flux-local CLI failure handling to better surface CLI errors. Previously it might appear to hang, but continued to chug away on the cluster.
=> Improve flux-local CLI failure handling

flux_local/git_repo.py, flux_local/kustomize.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/get.py, flux_local/tool/selector.py, flux_local/tool/test.py
This is needed to allow things like overriding load restrictions.
=> Add --kustomize-build-flags to allow override for kustomize build

action/diff/action.yml, action/test/action.yml
Allow setting --kustomize-build-flags in github actions
=> Allow setting --kustomize-build-flags in github actions

flux_local/manifest.py, tests/test_git_repo.py, tests/test_helm.py, tests/test_manifest.py, tests/testdata/cluster/infrastructure/configs/helm-repositories.yaml, tests/testdata/cluster/infrastructure/controllers/kustomization.yaml, tests/testdata/cluster/infrastructure/controllers/weave-gitops-release.yaml, tests/testdata/cluster2/apps/networking/kustomization.yaml, tests/testdata/cluster3/clusters/cluster3/cluster.yaml, tests/tool/testdata/build.yaml, tests/tool/testdata/build_helm.yaml, tests/tool/testdata/diff_hr_external_limit.yaml, tests/tool/testdata/diff_hr_limit.yaml, tests/tool/testdata/diff_ks_yaml_limit.yaml, tests/tool/testdata/get_cluster_yaml.yaml, tests/tool/testdata/get_hr.yaml, tests/tool/testdata/get_ks_wide.yaml
Found when testing against repo https://github.com/xUnholy/k8s-gitops
=> Allow sourceRef.namespace as optional when matching the HelmRelease

.github/workflows/flux-local-diff.yaml, .github/workflows/flux-local-test.yaml, action/diff/action.yml, action/test/action.yml
Add OCIRepository sources argument to flux diff and test.
=> Add OCIRepository sources to flux diff and test actions

flux_local/git_repo.py
=> Fix for OCIRepository relative paths

flux_local/tool/test.py, tests/testdata/cluster5/README.md, tests/testdata/cluster5/clusters/prod/flux-system/gotk-sync.yaml, tests/testdata/cluster5/clusters/prod/flux-system/kustomization.yaml, tests/testdata/cluster5/clusters/prod/infrastructure.yaml, tests/testdata/cluster5/infrastructure/configs/cluster-policies.yaml, tests/testdata/cluster5/infrastructure/configs/helm-repositories.yaml, tests/testdata/cluster5/infrastructure/configs/kustomization.yaml, tests/testdata/cluster5/infrastructure/controllers/kustomization.yaml, tests/testdata/cluster5/infrastructure/controllers/metallb-release.yaml, tests/testdata/cluster5/infrastructure/controllers/weave-gitops-release.yaml
Issue #245
```
$ flux-local test -v --path tests/testdata/cluster5/ 
======================================= test session starts ========================================
collected 1 item                                                                                   
tests/testdata/cluster5/clusters/prod::flux-system::kustomization PASSED                     [100%]
======================================== 1 passed in 0.10s =========================================
```
```
$ flux-local test -v -A --path tests/testdata/cluster5/ 
======================================= test session starts ========================================
collected 3 items                                                                                  
tests/testdata/cluster5/clusters/prod::infra-configs::kustomiza …
```
=> Correctly handle kustomization namespace for flux test

flux_local/helm.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/selector.py, flux_local/tool/test.py, flux_local/tool/visitor.py, tests/testdata/cluster3/README.md, tests/testdata/cluster5/README.md, tests/testdata/cluster6/renovate/kustomization.yaml, tests/testdata/cluster6/renovate/release.yaml, tests/testdata/cluster6/renovate/repository.yaml, tests/tool/testdata/build6.yaml, tests/tool/testdata/build_helm6.yaml, tests/tool/testdata/diff_hr6.yaml, tests/tool/testdata/get_cluster6.yaml, tests/tool/testdata/get_hr6.yaml, tests/tool/testdata/get_ks6.yaml
This changes the `Helm.template` api which previously had a set of boolean arguments to use an `Options` class.
Add tests that reproduce #251 including a copy of the provided test repo
=> Improve support for api-versions in CLI tools

CONTRIBUTING.md, flux_local/__init__.py, flux_local/helm.py, flux_local/tool/__init__.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/flux_local.py, flux_local/tool/test.py
Documentation improvements:
- Add descriptions to each CLI command
- Improve helm options pdoc
- re-organize cli command line flags
=> Cleanup and improve documentation

action/diff/action.yml
=> Add api-versions flag to diff action for consistency

.github/workflows/flux-local-diff.yaml, .github/workflows/flux-local-test.yaml, action/diff/action.yml, action/test/action.yml, flux_local/git_repo.py, flux_local/manifest.py, flux_local/tool/selector.py, tests/test_git_repo.py, tests/tool/testdata/get_cluster3.yaml
Allows restricting kustomizations to a specific set that should be included in the cluster.
Issue #283
=> Update --sources to allow restricting to specific GitRepository

.github/workflows/lint.yaml
Update workflow with ruff action
=> Update workflow with ruff action

flux_local/git_repo.py, flux_local/kustomize.py, flux_local/manifest.py, tests/test_kustomize.py, tests/testdata/cluster2/apps/networking/ingress-nginx/app/helmrelease.yaml, tests/testdata/cluster2/apps/networking/ingress-nginx/app/kustomization.yaml, tests/testdata/cluster2/apps/networking/ingress-nginx/ks.yaml
Test a cluster using targetNamespace without a namespace in the HelmRelease
Issue #387
=> Add support for targetNamespace in Fluxtomization

Dockerfile
Add flux dependency in development environment to prepare for calling `flux build`
Issue #390
=> Add flux dependency in development environment

pytest.ini, tests/testdata/cluster3/namespaces/base/podinfo/kustomization.yaml, tests/testdata/cluster3/namespaces/base/podinfo/release.yaml, tests/testdata/cluster3/namespaces/base/podinfo/repository.yaml, tests/tool/__snapshots__/test_get_hr.ambr
Increase coverage for cluster3 in preparation for additional rewriting.
=> Increase coverage for cluster3

pytest.ini, tests/__snapshots__/test_git_repo.ambr, tests/test_git_repo.py
=> Improve test coverage for cluster3 cases

renovate.json5
Update Renovate configuration to support upgrading versions in the Dockerfile
=> Renovate Dockerfile and versions

README.md
Update documentation examples to include flux cli
Issue #390
=> Update documentation examples to include flux cli

.github/workflows/pages.yaml
Reverts allenporter/flux-local#431
=> Revert "Update actions/upload-pages-artifact action to v3"

.github/workflows/pages.yaml
Reverts allenporter/flux-local#430
=> Revert "Update actions/deploy-pages action to v4"

.github/workflows/python-package.yaml, Dockerfile, action/diff/action.yml, action/test/action.yml, requirements.txt
=> Enable caching of package dependencies

.github/workflows/container-test.yaml
Hopefully this logic is correct so that main also builds
=> fix: update logic in container test to build on main

.github/workflows/python-package.yaml, flux_local/manifest.py, setup.cfg, tests/test_manifest.py
Move away from the pydantic v1 deprecated apis.
=> Upgrade to pydantic v2 APIs

README.md
Fix mistakes in example actions.
=> Update README.md to fix examples

tests/testdata/cluster/apps/prod/podinfo-values.yaml, tests/testdata/cluster/clusters/prod/apps.yaml, tests/tool/__snapshots__/test_build.ambr
=> Exercise postBuild.substituteFrom in tests

flux_local/git_repo.py
Replace queue.Queue with a collection
Pre-requisite for issue #617
=> Code simplification: Replace queue.Queue with a collection

flux_local/git_repo.py, flux_local/manifest.py
Simplify kustomization updates to prepare for adding dependency tracking.
Issue #617
=> Code cleanup: Make kustomization updates happen in place

flux_local/git_repo.py
Improve spelling, and fix typing or lint errors
=> Code lint improvements

README.md
README improvements, such as cleaning up stale versions, fixing markdown, and other misc small tweaks.
=> README improvements and cleanup

requirements.txt
=> Remove "-e ." when installing package requirements

flux_local/resource_diff.py, flux_local/tool/build.py, flux_local/tool/diff.py, flux_local/tool/get.py, flux_local/visitor.py, tests/test_visitor.py
Preparation for adding additional functionality in #817 that needs lower level unit tests.
=> Move resource diff and visitor logic to primary library directory

flux_local/tool/format.py, flux_local/tool/get.py, tests/tool/__snapshots__/test_get_cluster.ambr, tests/tool/test_get_cluster.py
=> Add `get cluster --only-images` flag to limit output

flux_local/git_repo.py, flux_local/manifest.py, tests/test_git_repo.py, tests/testdata/cluster/apps/prod/podinfo-values.yaml, tests/testdata/cluster/clusters/prod/apps.yaml, tests/testdata/cluster2/apps/monitoring/kubernetes-dashboard/app/kustomization.yaml, tests/tool/__snapshots__/test_build.ambr, tests/tool/__snapshots__/test_diff_ks.ambr
=> Add label selector in internal code that walks the repo and matches Kustomization and HelmReleases

flux_local/helm.py, flux_local/manifest.py
=> Pass OCIRepository chart ref tag to helm --version

flux_local/tool/get.py, tests/tool/__snapshots__/test_get_cluster.ambr, tests/tool/test_get_cluster.py
=> Fix OCIRepository support in `get cluster`

flux_local/helm.py, flux_local/manifest.py, tests/testdata/cluster9/apps/podinfo/podinfo.yaml, tests/tool/__snapshots__/test_build.ambr
=> Add support for HelmRelease disableSchemaValidation and disableOpenAPIValidation

flux_local/helm.py, flux_local/manifest.py, tests/test_helm.py, tests/testdata/cluster/infrastructure/controllers/weave-gitops-release.yaml, tests/testdata/cluster5/weave-gitops-release.yaml, tests/tool/__snapshots__/test_build.ambr, tests/tool/__snapshots__/test_get_cluster.ambr, tests/tool/__snapshots__/test_get_hr.ambr
This is a PoC PR to fix #865.
I've thought to add some tests, but, from what I see, contents of `test_data` is reused across many tests, so any changes to one `HelmRelease` manifest would have to be propagated across many unrelated tests. To make sure I don't necessarily cause a big diff, I'd like to ask what the best way to move forward would be (Which files to pick for the tests? Should an additional `HelmRelease` be introduced or better to modify an existing one?).
=> feat(helm): add support for targetNamespace

flux_local/values.py, tests/__snapshots__/test_values.ambr, tests/test_manifest.py, tests/test_values.py, tests/testdata/cluster8/apps/podinfo.yaml, tests/tool/__snapshots__/test_build.ambr
#870 Should fix the helm ValuesFrom escaping of dot notation.
=> Fix helm valuesFrom escape dot notation

flux_local/git_repo.py, flux_local/tool/diff.py
=> Improve handling of relative paths

flux_local/DESIGN.md
Propose a new design for the system that will allow improvements for sources.
=> Propose a new design for the system

flux_local/source_controller/__init__.py, flux_local/source_controller/artifact.py, flux_local/source_controller/git.py, flux_local/source_controller/oci.py, flux_local/source_controller/source_controller.py, flux_local/store/artifact.py, flux_local/store/in_memory.py, flux_local/store/store.py, tests/source_controller/test_source_controller.py, tests/store/test_in_memory.py
Add a Source Controller for reconciling external git repositories.
Issue: #862, #753
=> Add an initial source controller

flux_local/kustomize_controller/__init__.py, flux_local/kustomize_controller/artifact.py, flux_local/kustomize_controller/controller.py, flux_local/manifest.py, flux_local/source_controller/git.py, flux_local/source_controller/source_controller.py, flux_local/store/__init__.py, tests/kustomize_controller/__init__.py, tests/kustomize_controller/conftest.py, tests/kustomize_controller/test_controller.py, tests/source_controller/test_source_controller.py
=> Add a Kustomization Controller

flux_local/git_repo.py, flux_local/helm.py, flux_local/helm_controller/__init__.py, flux_local/helm_controller/artifact.py, flux_local/helm_controller/controller.py, flux_local/kustomize_controller/controller.py, flux_local/manifest.py, flux_local/source_controller/source_controller.py, flux_local/store/in_memory.py, flux_local/store/status.py, tests/helm_controller/test_controller.py, tests/store/test_in_memory.py
=> Add a HelmController

flux_local/helm.py, flux_local/manifest.py, tests/test_manifest.py, tests/tool/__snapshots__/test_get_cluster.ambr
Parse digest, semvar, etc in addition to tag
=> Improve OCIRepository version handling

flux_local/helm.py, flux_local/helm_controller/artifact.py, flux_local/helm_controller/controller.py, flux_local/kustomize_controller/controller.py, flux_local/manifest.py, flux_local/source_controller/artifact.py, flux_local/source_controller/git.py, flux_local/source_controller/oci.py, flux_local/store/artifact.py, flux_local/store/in_memory.py, flux_local/store/store.py, requirements.txt, requirements_dev.txt, setup.cfg, tests/helm_controller/test_controller.py, tests/kustomize_controller/test_controller.py, tests/source_controller/test_source_controller.py, tests/test_manifest.py
=> Improve Artifact support for OCI Artfacts in new controllers

flux_local/helm_controller/controller.py, tests/helm_controller/__snapshots__/test_controller.ambr, tests/helm_controller/test_controller.py
=> Update helm controller to apply objects to the cluster

.devcontainer/Dockerfile, Dockerfile
https://github.com/helm/helm/issues/30890
=> Rollback Helm to 3.17.3

.github/workflows/publish.yaml
=> Revert uv for project publish

tests/testdata/cluster7/flux/apps/cloudflare/release.yaml, tests/testdata/cluster7/flux/apps/unifi-controller/release.yaml, tests/testdata/cluster7/flux/charts/app-template.yaml
=> Update app-template test charts

flux_local/resource_diff.py, tests/test_resource_diff.py
=> Ensure that all HelmReleases are diffed on upstream dep changes

flux_local/helm_controller/controller.py, flux_local/kustomize_controller/controller.py, flux_local/manifest.py, flux_local/orchestrator/loader.py, flux_local/tool/shell/repl.py
Fix exception handling and logspam when building resources
=> Steamline error logging in flux shell

flux_local/git_repo.py, flux_local/orchestrator/orchestrator.py, tests/testdata/cluster10/apps/dex-k8s-authenticator/kustomization.yaml, tests/testdata/cluster10/apps/dex-k8s-authenticator/release.yaml, tests/testdata/cluster10/apps/dex-k8s-authenticator/repository.yaml, tests/tool/__snapshots__/test_build_ks.ambr, tests/tool/test_build_ks.py
=> Improve effectiveness of --skip-invalid-kustomization-paths for more cases
